export type { KnowledgeFactRepository } from './knowledge-fact-repository.js'
export type { KnowledgeGraphRepository } from './knowledge-graph-repository.js'
export type { HypothesisRepository } from './hypothesis-repository.js'
export type { EvidenceRequestRepository } from './evidence-request-repository.js'
export type { ResearchPlanRepository } from './research-plan-repository.js'
export type { LearningCycleRepository } from './learning-cycle-repository.js'
